#!/bin/env bash

AUTHOR="$PREFIX/share/kode"

#colors
R='\033[1;31m'
G='\033[1;32m'
W='\033[1;37m'
off='\033[0m'
t='        '


header()
{
printf "***********************************************#\n" 
printf "%-15s %s %-30s %s\n" "# Project title" ':'  $1 '#' 
printf "%-15s %s %-30s %s\n" "# Description" ':' "" '#' 
printf "%-15s %s %-30s %s\n" "# Author" ':' "$(< $AUTHOR/author.name)" '#' 
printf "%-15s %s %-30s %s\n" "# Last updated" ':'  "$(date  '+%a %d %b %y   %r')" '#' 
printf "%-15s %s %-30s %s\n" "# Notes" ":" ""  '#'     
printf "#***********************************************" 

}

shebang()
{
        environment=$( [[ "$1" =~ .\.py$ ]] && echo python3 || echo bash )
        echo "#!$(which env) $environment" > $1
}


set_author()
{
        if [[ ! -d $AUTHOR ]]
        then
                mkdir -p $AUTHOR
                touch $AUTHOR/author.name
        fi

        echo -e "${R} >>${W} Enter author's name :${off} \c"
        read AUTHOR_NAME

        printf "%.30s" "$AUTHOR_NAME" > $AUTHOR/author.name
        echo -e "${G} >>${W} Author name $AUTHOR_NAME set successfully"
}

#file_exist()
#init()

help()
{
        echo -e "Usage : ${W}kode${off} [option] [file...]" 
        echo -e " -h    --help      Print help" 
        echo -e " -v    --version   Print version"
        echo -e " -a    --author    Set author name" 
}

version()
{
        echo "kode v0.4"
        echo "A bash script to add header in your codes"
}

echo -e "/*$(header $1)*/\n" >> $1
echo -e "#*$(header $1)*#\n" >> $1

while [[ -n "$1" ]]; do
    case $1 in
        "-h" | "--help" )
                help ;;

        "-v" | "--version" )
                version ;;

        "-a" | "--author" )
               set_author ;;

        [!-]* )
            [[ -f "$1" ]] && file_exist $1     
            
            [[ $? -eq 0 && ! -n "$2" ]] && editor $1 ;;

        * )
                echo
            echo "$1 is Invalid Option"
            echo "Try \"-h\" or \"--h\" for Help!"
            echo
    esac
    shift
done

