#!/bin/env bash


header()
{
printf "***********************************************#\n" 
printf "%-15s %s %-30s %s\n" "# Project title" ':'  $1 '#' 
printf "%-15s %s %-30s %s\n" "# Description" ':' "" '#' 
printf "%-15s %s %-30s %s\n" "# Author" ':' Laraib07 '#' 
printf "%-15s %s %-30s %s\n" "# Last updated" ':'  "$(date)" '#' 
printf "%-15s %s %-30s %s\n" "# Notes" ":" ""  '#'     
printf "#***********************************************" 

}

shebang()
{
        environment=$( [[ "$1" =~ .\.py$ ]] && echo python3 || echo bash )
        touch $1
        echo "#!$(which env) $environment" > $1
        chmod u+x $1
}
printf "/*$(header $1)*/\n" >> $1
printf "#*$(header $1)*#\n" >> $1

