#!/bin/env bash

#************************************************#
#                                                #
#   kode v1.0                                    #
#   A bash script to add header in your code.    #
#   Author : https://github.com/laraib07         #
#                                                #
#************************************************#

#colors
R='\033[1;31m'
G='\033[1;32m'
W='\033[1;37m'
off='\033[0m'

banner()
{
        clear
        echo -e ${R}
        echo -e "  ████████████████████████"
        echo -e "  █▄─█─▄█─▄▄─█▄─▄▄▀█▄─▄▄─█"
        echo -e "  ██─▄▀██─██─██─██─██─▄█▀█"
        echo -e "  ▀▄▄▀▄▄▀▄▄▄▄▀▄▄▄▄▀▀▄▄▄▄▄▀"
        echo -e ${off}
}

set_author()
{
        echo -e "\n${R} ≫${W} Enter author's name :${off} \c"
        read AUTHOR_NAME

        AUTHOR_NAME=$(printf "%.30s" "$AUTHOR_NAME")
        sed -i "0,/^AUTHOR.*/{s//AUTHOR=\"${AUTHOR_NAME}\"/}" ~/.kode.config

        if [ $? -gt 0 ]
        then
                echo -e "${G} ≫${W} Author name $AUTHOR_NAME set successfully."
        fi
}

set_text_editor()
{
        false
        while [ $? -gt 0 ]
        do
                echo -e "\n${R} ≫${W} Enter text editor :${off} \c"
                read

                which $REPLY > /dev/null
                if [ $? -gt 0 ]
                then
                        echo -e "${R} ≫ error${W} : $REPLY not found"
                        echo -ne "   try again\r"

                else
                        sed -i "0,/^TXT_EDITOR.*/{s//TXT_EDITOR=${REPLY}/}" ~/.kode.config

                        echo -e "${G} ≫${W} $REPLY set successfully."

                fi
                which $REPLY > /dev/null
        done
}

make_config()
{
        touch ~/.kode.config
        echo 'AUTHOR="no_name"'>> ~/.kode.config
        echo 'TXT_EDITOR=nano' >> ~/.kode.config
        echo 'DEFAULT_TXT_EDITOR="nano"' >>~/.kode.config

}

download_kode()
{
        
        echo -e "\n${R} ≫${W} Download via :"
        echo -e "    [c] curl"
        echo -e "    [w] wget"
        echo -e "\n${R} ≫${W} Enter choice(default : w) : \c"
        read reply

        [[ -z "$reply" ]] && reply=w

        case $reply in
                [cC])
        
                curl -O  https://raw.githubusercontent.com/laraib07/kode/master/kode && chmod 755 kode 
                ;;

                [wW])

                wget https://raw.githubusercontent.com/laraib07/kode/master/kode && chmod 755 kode
                ;;
        esac
}


banner
download_kode
make_config
set_author
echo
set_text_editor

exit 0
